spring.datasource.url = jdbc:postgresql://localhost:5432/shopflow
spring.datasource.username = ali
spring.datasource.password = 23393540

spring.application.name=shopflow

spring.jpa.hibernate.ddl-auto=none